---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
```{r}
activity <- read.csv(unz('activity.zip', 'activity.csv'))
activity$date <- as.Date(activity$date, format='%Y-%m-%d')
```



## What is mean total number of steps taken per day?
```{r}
dailysteps <- aggregate(activity$steps, by=list(activity$date), FUN=sum)
hist(dailysteps$x, breaks=8, main="Distribution of daily step totals", xlab="Amount of steps", ylab="Number of days")
mean(dailysteps$x, na.rm=TRUE)
median(dailysteps$x, na.rm=TRUE)
```



## What is the average daily activity pattern?
```{r}
avginterval <- aggregate(steps ~ interval, data=activity, FUN=mean, na.rm=TRUE)
plot(avginterval, type='l', main="Average step total per 5-minute interval", xlab="Time of day", ylab="Amount of steps")
avginterval[which.max(avginterval$steps), 'interval']
```



## Imputing missing values
```{r}
sum(is.na(activity$steps))
```

The missing data was filled with the correspondent interval averages shown in the latest plot.
```{r}
activity[is.na(activity$steps), 1] <-
  sapply(activity[is.na(activity$steps), 3],
         function(row) avginterval[avginterval$interval == row, 2])
```

```{r}
dailysteps <- aggregate(activity$steps, by=list(activity$date), FUN=sum)
hist(dailysteps$x, breaks=8, main="Distribution of daily step totals", xlab="Amount of steps", ylab="Number of days")
mean(dailysteps$x)
median(dailysteps$x)
```

## Are there differences in activity patterns between weekdays and weekends?
```{r}
weekends <- weekdays(activity$date) %in% c('Saturday', 'Sunday')
activity$daytype <- factor(weekends, labels=c('weekday', 'weekend'))
avginterval.daytype <- aggregate(steps ~ interval + daytype, data=activity, FUN=mean)

library(lattice)
xyplot(steps ~ interval | daytype, avginterval.daytype, xlab='Interval', ylab='Number of steps', type='l', layout=c(1, 2))
```
